### PR TITLE
Update neofetch

### PR DESCRIPTION
**Pull request by quintenvandamme**
https://github.com/dylanaraps/neofetch/commit/9818199c7323c5781ff398893d70c4e9dc49e0b9

### CODE REVIEW

**Comment by HexaOneOfficial** [comment]
updated to https://github.com/dylanaraps/neofetch/pull/1592

**Comment by HexaOneOfficial** [comment]
updated to https://github.com/dylanaraps/neofetch/pull/1593

**Comment by HexaOneOfficial** [comment]
updated to dylanaraps/neofetch#1596

**Comment by HexaOneOfficial** [comment]
updated to dylanaraps/neofetch#1607

**Comment by HexaOneOfficial** [comment]
updated to dylanaraps/neofetch#1613

**Comment by HexaOneOfficial** [comment]
updated to dylanaraps/neofetch#1614

**Comment by HexaOneOfficial** [comment]
updated to dylanaraps/neofetch#1611

**Comment by HexaOneOfficial** [comment]
updated to latest commit

**Comment by HexaOneOfficial** [comment]
updated to master

**Comment by nmcain** [comment]
how are there conflicts here xD

**Comment by HexaOneOfficial** [comment]
idk just remove the content are paste my own in

**Comment by quintenvandamme** [comment]
see https://github.com/dahliaOS/packages/blob/main/git.dylanaraps.neofetch.dap

**Pull request closed without merging**
